### ISSUE TITLE
Error when applying it to WMS

### ISSUE THREAD

**Issue by pcav** [PavelVeselsky/fft-convolution-filter#5]
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/fft-convolution-filter-master/fft_filter.py", line 221, in run
    add_layer=self.dlg.check_add.isChecked()
  File "/home/paolo/.qgis2/python/plugins/fft-convolution-filter-master/fft_filter.py", line 241, in fft_convolution
    new_crs = new_crs
  File "/home/paolo/.qgis2/python/plugins/fft-convolution-filter-master/fft_filter.py", line 445, in gaussian_filter
    with rasterio.open(in_path,'r') as in_raster:
  File "/usr/lib/python2.7/dist-packages/rasterio/**init**.py", line 118, in open
    s.start()
  File "rasterio/_base.pyx", line 67, in rasterio._base.DatasetReader.start (rasterio/_base.c:2307)
  File "rasterio/_err.pyx", line 67, in rasterio._err.GDALErrCtxManager.__exit__ (rasterio/_err.c:944)
IOError: `crs=EPSG:3003&dpiMode=7&format=image/png&layers=rt_ofc.10k13&styles=&url=http://www502.regione.toscana.it/wmsraster/com.rt.wms.RTmap/wms?map%3Dwmsofc' does not exist in the file system,
and is not recognised as a supported dataset name.
# 

WMS should either be supported, or not listed on the dropdown of available layers.

**Comment by PavelVeselsky** [comment]
I will add WMS support to some future version. In 0.1.3, I will let the plugin end cleanly with some "sorry" message while applied to a WMS layer.
